### Lisää blogi
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Ensimmäinen blogi",
  "author": "Sofiya",
  "url": "https://fullstackopen.com/osa4/sovelluksen_rakenne_ja_testauksen_alkeet#node-sovellusten-testaaminen",
  "likes": 9
}

### Hae kaikki blogit
GET http://localhost:3003/api/blogs
